#Maximum number of players allowed in an expedition. The UI might not look good with more than 4 players
# Default: 4
# Range: 1 ~ 100
maxExpeditionPlayerCount = 4
#Number of ticks that an expedition should be open for others to join. Is displayed as seconds ingame
# Default: 600
# Range: > 1
expeditionLobbyTtl = 600
#Number of ticks that a player has to access the same one again. Is displayed as hours, minutes and seconds ingame
# Default: 1728000
# Range: > 1
expeditionCooldown = 1728000
#Distance between the expedition structures in chunks
# Default: 100
# Range: > 10
distanceBetweenExpeditionStructures = 100
#Enables the recipe for the hub anchor that is needed to enter the hub. If you disable this setting, you will have to implement another way to get to the hub yourself
hubAnchorRecipeEnabled = true
#Number of chunks of a structure that are generated in one batch. Higher values lead to longer loading times but also lower lag spikes
# Default: 2
# Range: 1 ~ 5
structureGenerationBatchSize = 2
