name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - run: ./bin/update-pakku.sh
      - run: ./bin/pakku export

  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TAG: ${{ github.run_number }}
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - id: info
        run: echo "version=$(grep version pakku.json | cut -d'"' -f 4).${TAG}" >> "$GITHUB_OUTPUT"
      - run: sudo apt install -y devscripts build-essential debhelper-compat default-jre unzip
      - run: make VERSION=${{ steps.info.outputs.version }} dist
      - run: gh release create --title "Build ${{ steps.info.outputs.version }}" ${{ steps.info.outputs.version }} dist/*
