name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - run: ./bin/update-pakku.sh
      - run: ./bin/pakku export

  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TAG: ${{ github.run_number }}
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - id: info
        run: echo "version=3.${TAG}" >> "$GITHUB_OUTPUT"
      - run: sudo apt update
      - run: sudo apt install -y devscripts build-essential debhelper-compat default-jre unzip python3

      # Download neoforge, lego, etc.
      - run: make VERSION=${{ steps.info.outputs.version }} cache

      # Fetch mods.
      - run: make VERSION=${{ steps.info.outputs.version }} mods

      # Build build/pristine/ (install neoforge, extract mods from zip file, etc)
      - run: make VERSION=${{ steps.info.outputs.version }} pristine

      # Prepare build/deb/
      - run: make VERSION=${{ steps.info.outputs.version }} build/deb

      # Actually run debuild and such.
      - run: make VERSION=${{ steps.info.outputs.version }} dist

      # Push to GitHub Releases.
      - run: gh release create --title "Build ${{ steps.info.outputs.version }}" ${{ steps.info.outputs.version }} dist/*
